### ISSUE TITLE
Release gT 0.9

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-translate#163]
# Release of gatewayTranslate v0.9.x

## Preconditions

- [x] The develop branch has all changes merged for the next release
- [x] The develop branch has the semver for the next release
- [x] QA has signed off on the work (including tested against production)
- [x] Release notes are prepared

## Tasks

- [x] create a release branch from develop, named by the release semver: release-v0.9.0
- [x] create [PR](https://github.com/unfoldingWord/gateway-translate/pull/167) to merge release branch into main and merge (**do not delete branch after merge**)
- [x] tag develop: git tag v0.9.0 && git push --tags
- [x] cut a release from the release branch
- [x] add to the release the notes and any assets
- [x] announce on forum.door43.org

# Original Text of Issue
GATEWAYEDIT steps:

- Release Steps:
  - [x]  configure netlify to auto-build release branch `release-v1.0.0` (add as additional branch to Deploy contexts under https://app.netlify.com/sites/gateway-edit/settings/deploys)
  - [x]  create release branch `release-v1.0.0`
  - [x]  Ping QA that release branch is ready for testing (https://release-v1-0-0--gateway-edit.netlify.app/)

- When QA has OK'd release branch, make final release by merging to main:
  - [x] Create PR from `release-v1.0.0` branch to main branch.
  - [x] Merge pull request `release-v1.0.0` branch to main . New version is v1.0.0 build: ?\
  - [x] Ping QA that release is live at https://gatewayedit.com/
  - [x] Final Go ahead for publish from QA
  - [x] Create & push git tag
  - [x] Publish release notes.
  - [x] Create release notes and create release on github
  - [ ] Announce on forum.door43.org

**Comment by mandolyte** [comment]
Here is the "pinned" discord post where I have kept my notes on what to do to release gA. This should be compared with the above for a final checklist.


Release Processes

Note 1: Prerequisites and one time activities are included at the end of this post.

Note 2: Pull Requests (PRs) are the mechanism used to do merges and they should be reviewed. In the below, for the sake of brevity, PRs are not mentioned.

Preconditions

a. The develop branch has all changes merged that are supposed to be in the next release
b. QA has signed off on the work
c. Release notes are prepared

Tasks
 
1. create a release branch from develop, named by the release semver
2. merge release branch into main
3. tag develop: git tag <semver> && git push --tags
4. cut a release from the release branch
5. add to the release the notes and any assets

Expected Outcome

1. At this point, in time the main, develop, and release branches will be identical. In addition, the release itself will be the same code.
2. There will be two netlify links, one for develop and one for main. The code in both will be identical (after netlify produces the builds and deploys them)

Process for Bug Fixes

If a bug is found in production,then:
  - branch from the release branch a patch release
  - make, test changes
  - make release notes
  - merge into main
  - tag it
  - cut a patch release from main, named by the release semver
  - add to the release the notes and any assets

To incorporate bug fix into develop, do:
  - branch from develop
  - merge in the patch branch
  - resolve any conflicts and re-test
  - merge into develop

**Comment by BincyJ** [comment]
@mandolyte , @elsylambert , @Joel-C-Johnson , @birchamp  here are the release notes for 0.9. Feel free to edit if required . 

**gatewayTranslate 0.9** 

Pleased to announce the first release of gatewayTranslate (v0.9) , an online scripture editor application.

**Features:**
- Proskomma based scripture editor
- Ability to access scripture files from multiple sources including online and local files
- Indicate broken alignments
- Undo , redo edits

**Comment by elsylambert** [comment]
Released gT prod link: https://gateway-translate.netlify.app/login
Looks good.
